### PR TITLE
fixed spec import

### PR DESCRIPTION
**Pull request by jdoklovic**

### CODE REVIEW

**Comment by MunifTanjim** [comment]
Was it actually broken? :confused:

**Comment by jdoklovic** [comment]
> Was it actually broken?

The require statement was:
const { basePath, host, produces, schemes } = require('./spec')
which is breaks when I use yarn to build a project:

```
ERROR in ./node_modules/bitbucket/src/request/defaults.js
    Module not found: Error: Can't resolve './spec' in '/home/doklovic/data/gitstuff/vscode-bitbucket/node_modules/bitbucket/src/request'
```
changing to:
const { basePath, host, produces, schemes } = require('./spec.json')

fixes it.

**Comment by MunifTanjim** [comment]
That's strange. Node.js should resolve `.json` file without needing the extension on `require`.

**Comment by jdoklovic** [comment]
any chance we can get a minor version bump in npm?

**Pull request merged**
