### PR TITLE
new endpoints for BranchingModel

### PR DESCRIPTION
**Pull request by prkb**
Regenerated from current API spec to add the new endpoints for branching-model https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/branching-model

### CODE REVIEW

**Comment by MunifTanjim** [comment]
@prkb Can you suggest any names for these endpoints?

> https://github.com/MunifTanjim/node-bitbucket/pull/27/files#diff-f4cb3948f5fc9bf808755c5515dce641

**Comment by jdoklovic** [comment]
Why not repositories.getBranchingModel and repositories.updatetBranchingModelSettings

**Comment by prkb** [comment]
@MunifTanjim I added the new endpoint names to `api-names.json` and regenerated the routes. Please take a look.

**Comment by MunifTanjim** [comment]
@prkb I noticed that you made some manual changes to the `api-names.json` file. I've reverted those in https://github.com/MunifTanjim/node-bitbucket/pull/27/commits/229cabf44e711022d7499d73187131bafb8eed84. New endpoints is automatically inserted with `npm run generate:api-names` along with their `tags` from the API specification.

I also did a `git rebase` to the latest master's HEAD.

**Comment by MunifTanjim** [comment]
Released on [v1.14.0](https://www.npmjs.com/package/bitbucket/v/1.14.0) :tada:

**Pull request merged**
